### ISSUE TITLE
where is the source code

### ISSUE THREAD

**Issue by mwaaas** [mojaloop/mojaloop#1]

**Comment by jeffplesko** [comment]
The source code can be found here:  https://github.com/mojaloop/interop-devops/releases

**Comment by DavidNgugi** [comment]
haha i was wondering about the same

**Comment by bhcrosslake** [comment]
Interop-devops/releases has the latest downloadable/install-able bits. Since this is a microservice architecture, the source behind those bits is in all the different repos. Example: source for the central ledger service is in the central-ledger repo. We've added the interop-devops to the pinned repos to make it easier to find.
